name: smart_soliq_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  mask_text_input_formatter: ^2.9.0
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  get_storage: ^2.1.1
  fluttertoast: ^8.2.12
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.3
  internet_connection_checker: ^3.0.1
  package_info_plus: ^8.3.0
  webview_flutter: ^4.11.0
  qr_code_scanner_plus: ^2.0.10+1
  
  # webview_flutter_android: 

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



flutter:


  uses-material-design: true

  assets:
    - .env 
    - assets/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


flutter_icons:
  android: true
  ios: true
  # image_path: "assets/images/splash_logo.png"
  min_sdk_android: 21
  remove_alpfa_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/splash_logo.png"